[package]
name = "mrkc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
textwrap = "0.16.0"

[[bin]]
name = "mrkc"
path = "src/main.rs"
